// Generated by apps/backend/scripts/generate-openapi.ts -- do not edit.
// Run `pnpm --dir apps/backend run codegen` after changing a validator.

export type Branding = {
  id: string;
  name: string;
  logo_url: string | null;
  favicon_url: string | null;
  support_email: string | null;
};

export type NewsletterSettings = {
  id: string;
  enabled: boolean;
  audience_id: string | null;
  double_opt_in: boolean;
  consent_text: string | null;
  success_message: string | null;
  reply_to: string | null;
  checkout_opt_in: boolean;
  checkout_label: string | null;
};

export type NewsletterSubscriber = {
  id: string;
  email: string;
  status: "pending" | "subscribed" | "unsubscribed";
  source: string | null;
  consent_text: string | null;
  consent_at: string | null;
  confirmed_at: string | null;
  unsubscribed_at: string | null;
  resend_contact_id: string | null;
  sync_pending: boolean;
  sync_attempted_at: string | null;
  created_at: string;
  updated_at: string;
};

export type ResendAudience = {
  id: string;
  name: string;
};

export type Wishlist = {
  id: string | null;
  items: {
    id: string;
    product_id: string;
    product_variant_id: string | null;
    created_at: string;
  }[];
};

export type Customer = {
  id: string;
  email: string;
  first_name: string | null;
  last_name: string | null;
  phone: string | null;
  has_account: boolean;
  created_at: string;
};

export type AdminUpdateBrandingBody = {
  name?: string;
  logo_url?: string | null;
  favicon_url?: string | null;
  support_email?: string | null;
};

export type AdminUpdateNewsletterSettingsBody = {
  enabled?: boolean;
  audience_id?: string | null;
  double_opt_in?: boolean;
  consent_text?: string | null;
  success_message?: string | null;
  reply_to?: string | null;
  checkout_opt_in?: boolean;
  checkout_label?: string | null;
};

export type StoreNewsletterSubscribeBody = {
  email: string;
  source?: string;
};

export type StoreNewsletterTokenBody = {
  token: string;
};

export type StoreCreateSocialCustomerBody = {
  first_name?: string | null;
  last_name?: string | null;
};

export type StoreSetCustomerPasswordBody = {
  password: string;
};

export type StoreAddWishlistItemBody = {
  product_id: string;
  variant_id?: string | null;
};

export type StoreMergeWishlistBody = {
  wishlist_id: string;
};

export type AdminBrandingResponse = {
  branding: {
    id: string;
    name: string;
    logo_url: string | null;
    favicon_url: string | null;
    support_email: string | null;
  };
};

export type AdminNewsletterSettingsResponse = {
  settings: {
    id: string;
    enabled: boolean;
    audience_id: string | null;
    double_opt_in: boolean;
    consent_text: string | null;
    success_message: string | null;
    reply_to: string | null;
    checkout_opt_in: boolean;
    checkout_label: string | null;
  };
};

export type AdminNewsletterSubscribersResponse = {
  stats: {
    confirmed: number;
    pending: number;
    sync_pending: number;
  };
  subscribers: {
    id: string;
    email: string;
    status: "pending" | "subscribed" | "unsubscribed";
    source: string | null;
    consent_text: string | null;
    consent_at: string | null;
    confirmed_at: string | null;
    unsubscribed_at: string | null;
    resend_contact_id: string | null;
    sync_pending: boolean;
    sync_attempted_at: string | null;
    created_at: string;
    updated_at: string;
  }[];
  count: number;
  limit: number;
  offset: number;
};

export type AdminNewsletterAudiencesResponse = {
  audiences: {
    id: string;
    name: string;
  }[];
};

export type StoreNewsletterAckResponse = {
  success: boolean;
  message?: string;
  status?: string;
};

export type StoreWishlistResponse = {
  wishlist: {
    id: string | null;
    items: {
      id: string;
      product_id: string;
      product_variant_id: string | null;
      created_at: string;
    }[];
  };
};

export type StoreSocialCustomerResponse = {
  customer: {
    id: string;
    email: string;
    first_name: string | null;
    last_name: string | null;
    phone: string | null;
    has_account: boolean;
    created_at: string;
  };
  linked: boolean;
};

export type StoreSetCustomerPasswordResponse = {
  success: boolean;
};

export type ProductAlert = {
  id: string;
  product_id: string;
  variant_id: string | null;
  reason: "restock" | "launch";
  status: "waiting" | "sent" | "cancelled" | "failed";
  created_at: string;
  notified_at: string | null;
};

export type MarketingPreference = {
  status: "none" | "pending" | "subscribed" | "unsubscribed";
  available: boolean;
  consent_text: string | null;
};

export type StoreCreateProductAlertBody = {
  email?: string;
  variant_id?: string | null;
  marketing_opt_in?: boolean;
};

export type StoreCreateProductAlertResponse = {
  success: boolean;
  alert: {
    id: string;
    product_id: string;
    variant_id: string | null;
    reason: "restock" | "launch";
    status: "waiting" | "sent" | "cancelled" | "failed";
    created_at: string;
  } | null;
};

export type StoreProductAlertsResponse = {
  alerts: {
    id: string;
    product_id: string;
    variant_id: string | null;
    reason: "restock" | "launch";
    status: "waiting" | "sent" | "cancelled" | "failed";
    created_at: string;
    notified_at: string | null;
  }[];
};

export type StoreSetMarketingPreferenceBody = {
  subscribed: boolean;
};

export type StoreMarketingPreferenceResponse = {
  marketing: {
    status: "none" | "pending" | "subscribed" | "unsubscribed";
    available: boolean;
    consent_text: string | null;
  };
};

export type AdminSetProductComingSoonBody = {
  coming_soon: boolean;
};

export type SizeGuideTable = {
  columns: {
    key: string;
    label: string;
    type: "measurement" | "text";
  }[];
  rows: {
    size: string;
    values: Record<string, unknown>;
  }[];
};

export type StoreSizeGuide = {
  id: string;
  name: string;
  description: string | null;
  diagram_url: string | null;
  unit: string;
  columns: {
    key: string;
    label: string;
    type: "measurement" | "text";
  }[];
  rows: {
    size: string;
    values: Record<string, unknown>;
  }[];
};

export type StoreSizeGuideResponse = {
  size_guide: {
    id: string;
    name: string;
    description: string | null;
    diagram_url: string | null;
    unit: string;
    columns: {
      key: string;
      label: string;
      type: "measurement" | "text";
    }[];
    rows: {
      size: string;
      values: Record<string, unknown>;
    }[];
  } | null;
  source: "product" | "category" | "default" | null;
};

export type AdminSizeGuide = {
  id: string;
  name: string;
  description: string | null;
  diagram_url: string | null;
  table: {
    columns: {
      key: string;
      label: string;
      type: "measurement" | "text";
    }[];
    rows: {
      size: string;
      values: Record<string, unknown>;
    }[];
  };
  is_default: boolean;
  created_at: string;
  updated_at: string;
  product_count: number;
  categories: {
    id: string;
    name: string;
  }[];
};

export type AdminCreateSizeGuideBody = {
  name: string;
  description?: string | null;
  diagram_url?: string | null;
  table: {
    columns: {
      key: string;
      label: string;
      type: "measurement" | "text";
    }[];
    rows: {
      size: string;
      values: Record<string, unknown>;
    }[];
  };
  is_default?: boolean;
};

export type AdminUpdateSizeGuideBody = {
  name?: string;
  description?: string | null;
  diagram_url?: string | null;
  table?: {
    columns: {
      key: string;
      label: string;
      type: "measurement" | "text";
    }[];
    rows: {
      size: string;
      values: Record<string, unknown>;
    }[];
  };
  is_default?: boolean;
};

export type AdminSetSizeGuideBody = {
  size_guide_id: string | null;
};

export type StorefrontSettings = {
  id: string;
  new_badge_days: number;
  seo_title: string | null;
  seo_description: string | null;
  og_image_url: string | null;
  twitter_handle: string | null;
  social_links: Record<string, unknown>;
  allow_indexing: boolean;
  google_site_verification: string | null;
  homepage_hero: {
    enabled: boolean;
    eyebrow: string | null;
    title: string | null;
    description: string | null;
    desktop_image_url: string | null;
    mobile_image_url: string | null;
    desktop_video_url: string | null;
    mobile_video_url: string | null;
    cta_label: string | null;
    cta_url: string | null;
  };
  featured_collection_id: string | null;
  store_menu_cards: {
    target_type: "collection" | "category" | "product";
    target_id: string;
    image_url: string;
    mobile_image_url: string | null;
  }[];
  announcement_bar: {
    enabled: boolean;
    appearance: "light" | "dark";
    dismissible: boolean;
    items: {
      id: string;
      enabled: boolean;
      message: string;
      link_label: string | null;
      destination: unknown | null;
      starts_at: string | null;
      ends_at: string | null;
      promotion_id: string | null;
    }[];
  };
};

export type StoreAnnouncementsResponse = {
  appearance: "light" | "dark";
  dismissible: boolean;
  server_time: string;
  valid_until: string;
  items: {
    id: string;
    message: string;
    link_label: string | null;
    href: string | null;
    promotion_code: string | null;
    ends_at: string | null;
  }[];
};

export type AdminAnnouncementOptionsResponse = {
  options: {
    id: string;
    label: string;
  }[];
  count: number;
  offset: number;
  limit: number;
};

export type AdminUpdateStorefrontSettingsBody = {
  new_badge_days?: number;
  seo_title?: string | null;
  seo_description?: string | null;
  og_image_url?: string | null;
  twitter_handle?: string | null;
  social_links?: {
    instagram?: string | null;
    facebook?: string | null;
    tiktok?: string | null;
    x?: string | null;
    youtube?: string | null;
    pinterest?: string | null;
  };
  allow_indexing?: boolean;
  google_site_verification?: string | null;
  homepage_hero?: {
    enabled: boolean;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    desktop_image_url?: string | null;
    mobile_image_url?: string | null;
    desktop_video_url?: string | null;
    mobile_video_url?: string | null;
    cta_label?: string | null;
    cta_url?: string | null;
  };
  featured_collection_id?: string | null;
  store_menu_cards?: {
    target_type: "collection" | "category" | "product";
    target_id: string;
    image_url: string;
    mobile_image_url?: string | null;
  }[];
  announcement_bar?: {
    enabled: boolean;
    appearance: "light" | "dark";
    dismissible: boolean;
    items: {
      id: string;
      enabled: boolean;
      message: string;
      link_label: string | null;
      destination: unknown | null;
      starts_at: string | null;
      ends_at: string | null;
      promotion_id: string | null;
    }[];
  };
};

export type AdminStorefrontSettingsResponse = {
  settings: {
    id: string;
    new_badge_days: number;
    seo_title: string | null;
    seo_description: string | null;
    og_image_url: string | null;
    twitter_handle: string | null;
    social_links: Record<string, unknown>;
    allow_indexing: boolean;
    google_site_verification: string | null;
    homepage_hero: {
      enabled: boolean;
      eyebrow: string | null;
      title: string | null;
      description: string | null;
      desktop_image_url: string | null;
      mobile_image_url: string | null;
      desktop_video_url: string | null;
      mobile_video_url: string | null;
      cta_label: string | null;
      cta_url: string | null;
    };
    featured_collection_id: string | null;
    store_menu_cards: {
      target_type: "collection" | "category" | "product";
      target_id: string;
      image_url: string;
      mobile_image_url: string | null;
    }[];
    announcement_bar: {
      enabled: boolean;
      appearance: "light" | "dark";
      dismissible: boolean;
      items: {
        id: string;
        enabled: boolean;
        message: string;
        link_label: string | null;
        destination: unknown | null;
        starts_at: string | null;
        ends_at: string | null;
        promotion_id: string | null;
      }[];
    };
  };
};

export type AdminHomepageHeroHistoryResponse = {
  revisions: {
    id: string;
    hero: {
      enabled: boolean;
      eyebrow: string | null;
      title: string | null;
      description: string | null;
      desktop_image_url: string | null;
      mobile_image_url: string | null;
      desktop_video_url: string | null;
      mobile_video_url: string | null;
      cta_label: string | null;
      cta_url: string | null;
    };
    replaced_at: string;
    replaced_by: {
      id: string;
      email: string | null;
      name: string | null;
    } | null;
  }[];
};

export type StoreStorefrontSettingsResponse = {
  settings: {
    navigation: {
      store_menu_cards: {
        title: string;
        href: string;
        image_url: string;
        mobile_image_url: string | null;
      }[];
    };
    brand: {
      name: string;
      logo_url: string | null;
      favicon_url: string | null;
      support_email: string | null;
    };
    seo: {
      title: string | null;
      description: string | null;
      og_image_url: string | null;
      twitter_handle: string | null;
      social_links: {
        instagram: string | null;
        facebook: string | null;
        tiktok: string | null;
        x: string | null;
        youtube: string | null;
        pinterest: string | null;
      };
      allow_indexing: boolean;
      google_site_verification: string | null;
    };
    homepage: {
      hero: {
        enabled: boolean;
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        desktop_image_url: string | null;
        mobile_image_url: string | null;
        desktop_video_url: string | null;
        mobile_video_url: string | null;
        cta_label: string | null;
        cta_url: string | null;
      };
      featured_collection_id: string | null;
    };
    products: {
      new_badge_days: number;
    };
  };
};

export type StoreSearchProduct = {
  id: string;
  title: string;
  subtitle: string | null;
  description: string | null;
  handle: string;
  thumbnail: string | null;
  status: string;
  created_at: string;
  type: string | null;
  collection: string | null;
  collection_handle: string | null;
  categories: string[];
  category_handles: string[];
  tags: string[];
  sales_channel_ids: string[];
};

export type StoreSearchResponse = {
  products: {
    id: string;
    title: string;
    subtitle: string | null;
    description: string | null;
    handle: string;
    thumbnail: string | null;
    status: string;
    created_at: string;
    type: string | null;
    collection: string | null;
    collection_handle: string | null;
    categories: string[];
    category_handles: string[];
    tags: string[];
    sales_channel_ids: string[];
  }[];
  count: number;
  limit: number;
  offset: number;
  facets: Record<string, unknown>;
};

export type AdminCartReminderSettingsResponse = {
  settings: {
    id: string;
    enabled: boolean;
    first_delay_hours: number;
    second_delay_hours: number | null;
    third_delay_hours: number | null;
  };
};

export type AdminUpdateCartReminderSettingsBody = {
  enabled?: boolean;
  first_delay_hours?: number;
  second_delay_hours?: number | null;
  third_delay_hours?: number | null;
};

export type AdminCartReminderStatsResponse = {
  stats: {
    since: string;
    carts_reminded: number;
    carts_opened: number;
    orders_recovered: number;
    revenue_recovered: {
      currency_code: string;
      amount: number;
    }[];
    stopped: number;
  };
};

export type StoreCartReminderTokenBody = {
  token: string;
};

export type StoreRestoreCartResponse = {
  cart_id: string;
};

export type StoreStopCartRemindersResponse = {
  status: string;
};
