// Generated by apps/backend/scripts/generate-openapi.ts -- do not edit.
// Run `pnpm --dir apps/backend run codegen` after changing a validator.

export type Branding = {
  id: string;
  name: string;
  logo_url: string | null;
  support_email: string | null;
};

export type NewsletterSettings = {
  id: string;
  enabled: boolean;
  audience_id: string | null;
  double_opt_in: boolean;
  consent_text: string | null;
  success_message: string | null;
  reply_to: string | null;
  checkout_opt_in: boolean;
  checkout_label: string | null;
};

export type NewsletterSubscriber = {
  id: string;
  email: string;
  status: "pending" | "subscribed" | "unsubscribed";
  source: string | null;
  consent_text: string | null;
  consent_at: string | null;
  confirmed_at: string | null;
  unsubscribed_at: string | null;
  resend_contact_id: string | null;
  created_at: string;
  updated_at: string;
};

export type ResendAudience = {
  id: string;
  name: string;
};

export type Wishlist = {
  id: string | null;
  items: {
    id: string;
    product_id: string;
    product_variant_id: string | null;
    created_at: string;
  }[];
};

export type Customer = {
  id: string;
  email: string;
  first_name: string | null;
  last_name: string | null;
  phone: string | null;
  has_account: boolean;
  created_at: string;
};

export type AdminUpdateBrandingBody = {
  name?: string;
  logo_url?: string | null;
  support_email?: string | null;
};

export type AdminUpdateNewsletterSettingsBody = {
  enabled?: boolean;
  audience_id?: string | null;
  double_opt_in?: boolean;
  consent_text?: string | null;
  success_message?: string | null;
  reply_to?: string | null;
  checkout_opt_in?: boolean;
  checkout_label?: string | null;
};

export type StoreNewsletterSubscribeBody = {
  email: string;
  source?: string;
};

export type StoreNewsletterTokenBody = {
  token: string;
};

export type StoreCreateSocialCustomerBody = {
  first_name?: string | null;
  last_name?: string | null;
};

export type StoreSetCustomerPasswordBody = {
  password: string;
};

export type StoreAddWishlistItemBody = {
  product_id: string;
  variant_id?: string | null;
};

export type AdminBrandingResponse = {
  branding: {
    id: string;
    name: string;
    logo_url: string | null;
    support_email: string | null;
  };
};

export type AdminNewsletterSettingsResponse = {
  settings: {
    id: string;
    enabled: boolean;
    audience_id: string | null;
    double_opt_in: boolean;
    consent_text: string | null;
    success_message: string | null;
    reply_to: string | null;
    checkout_opt_in: boolean;
    checkout_label: string | null;
  };
};

export type AdminNewsletterSubscribersResponse = {
  subscribers: {
    id: string;
    email: string;
    status: "pending" | "subscribed" | "unsubscribed";
    source: string | null;
    consent_text: string | null;
    consent_at: string | null;
    confirmed_at: string | null;
    unsubscribed_at: string | null;
    resend_contact_id: string | null;
    created_at: string;
    updated_at: string;
  }[];
  count: number;
  limit: number;
  offset: number;
};

export type AdminNewsletterAudiencesResponse = {
  audiences: {
    id: string;
    name: string;
  }[];
};

export type StoreNewsletterAckResponse = {
  success: boolean;
  message?: string;
  status?: string;
};

export type StoreWishlistResponse = {
  wishlist: {
    id: string | null;
    items: {
      id: string;
      product_id: string;
      product_variant_id: string | null;
      created_at: string;
    }[];
  };
};

export type StoreSocialCustomerResponse = {
  customer: {
    id: string;
    email: string;
    first_name: string | null;
    last_name: string | null;
    phone: string | null;
    has_account: boolean;
    created_at: string;
  };
  linked: boolean;
};

export type StoreSetCustomerPasswordResponse = {
  success: boolean;
};
