// Generated by apps/backend/scripts/generate-openapi.ts -- do not edit.
// Run `pnpm --dir apps/backend run codegen` after changing a validator.

export type Branding = {
  id: string;
  name: string;
  logo_url: string | null;
  support_email: string | null;
};

export type NewsletterSettings = {
  id: string;
  enabled: boolean;
  audience_id: string | null;
  double_opt_in: boolean;
  consent_text: string | null;
  success_message: string | null;
  reply_to: string | null;
  checkout_opt_in: boolean;
  checkout_label: string | null;
};

export type NewsletterSubscriber = {
  id: string;
  email: string;
  status: "pending" | "subscribed" | "unsubscribed";
  source: string | null;
  consent_text: string | null;
  consent_at: string | null;
  confirmed_at: string | null;
  unsubscribed_at: string | null;
  resend_contact_id: string | null;
  created_at: string;
  updated_at: string;
};

export type ResendAudience = {
  id: string;
  name: string;
};

export type Wishlist = {
  id: string | null;
  items: {
    id: string;
    product_id: string;
    product_variant_id: string | null;
    created_at: string;
  }[];
};

export type Customer = {
  id: string;
  email: string;
  first_name: string | null;
  last_name: string | null;
  phone: string | null;
  has_account: boolean;
  created_at: string;
};

export type AdminUpdateBrandingBody = {
  name?: string;
  logo_url?: string | null;
  support_email?: string | null;
};

export type AdminUpdateNewsletterSettingsBody = {
  enabled?: boolean;
  audience_id?: string | null;
  double_opt_in?: boolean;
  consent_text?: string | null;
  success_message?: string | null;
  reply_to?: string | null;
  checkout_opt_in?: boolean;
  checkout_label?: string | null;
};

export type StoreNewsletterSubscribeBody = {
  email: string;
  source?: string;
};

export type StoreNewsletterTokenBody = {
  token: string;
};

export type StoreCreateSocialCustomerBody = {
  first_name?: string | null;
  last_name?: string | null;
};

export type StoreSetCustomerPasswordBody = {
  password: string;
};

export type StoreAddWishlistItemBody = {
  product_id: string;
  variant_id?: string | null;
};

export type StoreMergeWishlistBody = {
  wishlist_id: string;
};

export type AdminBrandingResponse = {
  branding: {
    id: string;
    name: string;
    logo_url: string | null;
    support_email: string | null;
  };
};

export type AdminNewsletterSettingsResponse = {
  settings: {
    id: string;
    enabled: boolean;
    audience_id: string | null;
    double_opt_in: boolean;
    consent_text: string | null;
    success_message: string | null;
    reply_to: string | null;
    checkout_opt_in: boolean;
    checkout_label: string | null;
  };
};

export type AdminNewsletterSubscribersResponse = {
  subscribers: {
    id: string;
    email: string;
    status: "pending" | "subscribed" | "unsubscribed";
    source: string | null;
    consent_text: string | null;
    consent_at: string | null;
    confirmed_at: string | null;
    unsubscribed_at: string | null;
    resend_contact_id: string | null;
    created_at: string;
    updated_at: string;
  }[];
  count: number;
  limit: number;
  offset: number;
};

export type AdminNewsletterAudiencesResponse = {
  audiences: {
    id: string;
    name: string;
  }[];
};

export type StoreNewsletterAckResponse = {
  success: boolean;
  message?: string;
  status?: string;
};

export type StoreWishlistResponse = {
  wishlist: {
    id: string | null;
    items: {
      id: string;
      product_id: string;
      product_variant_id: string | null;
      created_at: string;
    }[];
  };
};

export type StoreSocialCustomerResponse = {
  customer: {
    id: string;
    email: string;
    first_name: string | null;
    last_name: string | null;
    phone: string | null;
    has_account: boolean;
    created_at: string;
  };
  linked: boolean;
};

export type StoreSetCustomerPasswordResponse = {
  success: boolean;
};

export type ProductAlert = {
  id: string;
  product_id: string;
  variant_id: string | null;
  reason: "restock" | "launch";
  status: "waiting" | "sent" | "cancelled" | "failed";
  created_at: string;
  notified_at: string | null;
};

export type MarketingPreference = {
  status: "none" | "pending" | "subscribed" | "unsubscribed";
  available: boolean;
  consent_text: string | null;
};

export type StoreCreateProductAlertBody = {
  email?: string;
  variant_id?: string | null;
  marketing_opt_in?: boolean;
};

export type StoreCreateProductAlertResponse = {
  success: boolean;
  alert: {
    id: string;
    product_id: string;
    variant_id: string | null;
    reason: "restock" | "launch";
    status: "waiting" | "sent" | "cancelled" | "failed";
    created_at: string;
  } | null;
};

export type StoreProductAlertsResponse = {
  alerts: {
    id: string;
    product_id: string;
    variant_id: string | null;
    reason: "restock" | "launch";
    status: "waiting" | "sent" | "cancelled" | "failed";
    created_at: string;
    notified_at: string | null;
  }[];
};

export type StoreSetMarketingPreferenceBody = {
  subscribed: boolean;
};

export type StoreMarketingPreferenceResponse = {
  marketing: {
    status: "none" | "pending" | "subscribed" | "unsubscribed";
    available: boolean;
    consent_text: string | null;
  };
};

export type AdminSetProductComingSoonBody = {
  coming_soon: boolean;
};

export type SizeGuideTable = {
  columns: {
    key: string;
    label: string;
    type: "measurement" | "text";
  }[];
  rows: {
    size: string;
    values: Record<string, unknown>;
  }[];
};

export type StoreSizeGuide = {
  id: string;
  name: string;
  description: string | null;
  diagram_url: string | null;
  unit: string;
  columns: {
    key: string;
    label: string;
    type: "measurement" | "text";
  }[];
  rows: {
    size: string;
    values: Record<string, unknown>;
  }[];
};

export type StoreSizeGuideResponse = {
  size_guide: {
    id: string;
    name: string;
    description: string | null;
    diagram_url: string | null;
    unit: string;
    columns: {
      key: string;
      label: string;
      type: "measurement" | "text";
    }[];
    rows: {
      size: string;
      values: Record<string, unknown>;
    }[];
  } | null;
  source: "product" | "category" | "default" | null;
};

export type AdminSizeGuide = {
  id: string;
  name: string;
  description: string | null;
  diagram_url: string | null;
  table: {
    columns: {
      key: string;
      label: string;
      type: "measurement" | "text";
    }[];
    rows: {
      size: string;
      values: Record<string, unknown>;
    }[];
  };
  is_default: boolean;
  created_at: string;
  updated_at: string;
  product_count: number;
  categories: {
    id: string;
    name: string;
  }[];
};

export type AdminCreateSizeGuideBody = {
  name: string;
  description?: string | null;
  diagram_url?: string | null;
  table: {
    columns: {
      key: string;
      label: string;
      type: "measurement" | "text";
    }[];
    rows: {
      size: string;
      values: Record<string, unknown>;
    }[];
  };
  is_default?: boolean;
};

export type AdminUpdateSizeGuideBody = {
  name?: string;
  description?: string | null;
  diagram_url?: string | null;
  table?: {
    columns: {
      key: string;
      label: string;
      type: "measurement" | "text";
    }[];
    rows: {
      size: string;
      values: Record<string, unknown>;
    }[];
  };
  is_default?: boolean;
};

export type AdminSetSizeGuideBody = {
  size_guide_id: string | null;
};

export type StorefrontSettings = {
  id: string;
  new_badge_days: number;
};

export type AdminUpdateStorefrontSettingsBody = {
  new_badge_days?: number;
};

export type AdminStorefrontSettingsResponse = {
  settings: {
    id: string;
    new_badge_days: number;
  };
};

export type StoreStorefrontSettingsResponse = {
  settings: {
    new_badge_days: number;
  };
};

export type StoreSearchProduct = {
  id: string;
  title: string;
  subtitle: string | null;
  description: string | null;
  handle: string;
  thumbnail: string | null;
  status: string;
  created_at: string;
  type: string | null;
  collection: string | null;
  collection_handle: string | null;
  categories: string[];
  category_handles: string[];
  tags: string[];
  sales_channel_ids: string[];
};

export type StoreSearchResponse = {
  products: {
    id: string;
    title: string;
    subtitle: string | null;
    description: string | null;
    handle: string;
    thumbnail: string | null;
    status: string;
    created_at: string;
    type: string | null;
    collection: string | null;
    collection_handle: string | null;
    categories: string[];
    category_handles: string[];
    tags: string[];
    sales_channel_ids: string[];
  }[];
  count: number;
  limit: number;
  offset: number;
  facets: Record<string, unknown>;
};
